### ISSUE TITLE
Suggestion: suggest hasValue for optionals

### ISSUE THREAD

**Issue by erikpragt-connectid** [chrisly42/cajon-plugin#11]
We have the following code:

```
assertThat(response.getBody().get()).isEqualTo("pong");
```

where `response.getBody()` returns an optional String.

what I think would be a good suggestion, is the following:

```
assertThat(response.getBody()).hasValue("pong");
```

Could that be a reasonable addition to this plugin?

**Comment by chrisly42** [comment]
Hmmm... I'm confused. This should be included in the `AssertThatJava8Optional` inspection. From the Readme:

```
  from: assertThat(opt.get()).isEqualTo("foo");
    to: assertThat(opt).contains("foo");
```

It uses contains() though to which hasValue() is an alias.

I just checked the plugin manually and it does suggest the change in my case.

Can you produce a code fragment that does not come up with the inspection as expected? Thanks.
